### ISSUE TITLE
关于密钥

### ISSUE THREAD

**Issue by NepPure** [ACPudding/ZuZheng#1]
https://github.com/ACPudding/ZuZheng/blob/027e3b42163e4754de9c73bdd8259ee0f1631c1c/ZuZheng/CatAndMouseGame.cs#L27

大佬请问这个密钥是逆向工程找出来的吗，能否顺便抓一下ios bgo 的密钥，我看老版本的逆向工程这个代码应该是写在一起的，只是判断了一下平台

**Comment by NepPure** [comment]
这个Ios也能用

**Comment by ACPudding** [comment]
> 这个Ios也能用
资源解密密钥是通用的，不存在根据IOS/安卓区分。
BGO的话只是Masterdata的格式和日服完全不同，BGO用的Protobuf，日服/美服用加密Json

**Comment by NepPure** [comment]
https://github.com/hexstr/FGOAssetsModifyTool/issues/11#issuecomment-1229195091

AssertStorage是通用的，我这里留了个资源解密后的示例，ios的资源用相同的解密方法还是不能读取

感觉还是有区别，暂时没找到好办法

**Comment by ACPudding** [comment]
> [hexstr/FGOAssetsModifyTool#11 (comment)](https://github.com/hexstr/FGOAssetsModifyTool/issues/11#issuecomment-1229195091)
> 
> AssertStorage是通用的，我这里留了个资源解密后的示例，ios的资源用相同的解密方法还是不能读取
> 
> 感觉还是有区别，暂时没找到好办法

emmmm，确实有点区别。有点奇怪。

安卓：
`123cb01a8981ca0a7091e60f2e473bba0836bf9a,DATA0,1143200,1891747837,CharaGraph/301300,,1`
IOS：
`e1cf47a9361587654c9999a3cd90ac4401edd7c9,DATA0,636960,966933325,CharaGraph/301300,,1`

照理来说确实解密key是没问题的（否则会报Exception），看了下文件头完全不一样

![QQ截图20220828134801](https://user-images.githubusercontent.com/22544986/187059670-af605fee-75d3-4209-849e-9a43128c0357.png)
![QQ截图20220828134739](https://user-images.githubusercontent.com/22544986/187059672-6aa613e3-1a68-4f72-9623-72423514cc6a.png)

**Comment by ACPudding** [comment]
> [hexstr/FGOAssetsModifyTool#11 (comment)](https://github.com/hexstr/FGOAssetsModifyTool/issues/11#issuecomment-1229195091)
> 
> AssertStorage是通用的，我这里留了个资源解密后的示例，ios的资源用相同的解密方法还是不能读取
> 
> 感觉还是有区别，暂时没找到好办法

我试了一下，是解密时候偏移量有微调。
![QQ截图20220828140944](https://user-images.githubusercontent.com/22544986/187060306-dc509291-6c38-47f6-97bf-62b852d263d9.png)
问题出在MouseGame4

我试出来BGO的IOS是这样的:
`array[i] = (byte)(b2 ^ 205);
array[i + 1] = (byte)(b ^ 211);`

安卓是:
`array[i] = (byte)(b2 ^ 210);
array[i + 1] = (byte)(b ^ 206);`

**Comment by ACPudding** [comment]
试了一下你提供的黑杯的包，也是改一下MouseGame4里面的偏移量就能成功读取了。
![QQ截图20220828142416](https://user-images.githubusercontent.com/22544986/187060695-5dbf6f9d-6ece-4d69-a141-067c6ab9257c.png)

![QQ截图20220828142430](https://user-images.githubusercontent.com/22544986/187060700-32086ef1-c652-430b-b943-1d9e9c0d23ea.png)

**Comment by NepPure** [comment]
啊啊啊啊 超级感谢大佬 ios有救了！

原来是这样 学到新姿势了！

**Comment by ACPudding** [comment]
> 啊啊啊啊 超级感谢大佬 ios有救了！
> 
> 原来是这样 学到新姿势了！

应该就是双端本身在这个函数上就有偏移量的差异，因为基本不拆IOS的包所以一直没发现23333

怀疑日服也是一样的。
